default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: muscle_user
  password: securepassword
  host: localhost

development:
  <<: *default
  database: muscle_memory_development

test:
  <<: *default
  database: muscle_memory_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: "<%= ENV['DB_PASSWORD'] %>"
